src/components/Header/Header.js
src/var/config.js

context: https://trello.com/c/PW0TbujQ/220-add-link-to-main-site-on-logo

add link to main site on logo

---

src/state/query/saga.js

context: https://trello.com/c/yvg92UOQ/226-not-sending-filter-params

fix symbol length check

---

.gitmodules
README.md

This PR adds a [bfx-report-express](https://github.com/bitfinexcom/bfx-report-express/pull/1) submodule
- This PR depends on those PRs:
https://github.com/bitfinexcom/bfx-report-express/pull/1
https://github.com/bitfinexcom/bfx-report/pull/93

Add bfx-report-express submodule

---

src/state/sync/selectors.js

Small fix for selector when state.sync === undefined

fix for selector

---

public/locales/en-US/translations.json
public/locales/zh-TW/translations.json

context:　https://trello.com/c/9xn1cQxa/245-change-name

rename Funding Offers to Funding Bids & Offers

---

package-lock.json
package.json
public/locales/en-US/translations.json
public/locales/zh-TW/translations.json
src/components/SyncPrefButton/SyncPrefButton.js

context: https://trello.com/c/V3agPHVf/249-public-trades-breaks-on-sync-mode

fix sync button translation issue to show public trades page correctly

---

package-lock.json
package.json
scripts/copyFiles.js
src/locales/i18n.js

this PR
- use i18next-localstorage-backend to cache translations in localStorage https://github.com/i18next/i18next-localstorage-backend#getting-started
- use shelljs.cp in script to copy files

local cache translations by version 

---

src/state/symbols/utils.js

Adds support for both future pairs and currencies

Add support for futures

---

public/locales/en-US/translations.json
public/locales/zh-TW/translations.json
src/components/FundingCreditHistory/FundingCreditHistory.columns.js
src/components/FundingLoanHistory/FundingLoanHistory.columns.js
src/components/FundingOfferHistory/FundingOfferHistory.columns.js
src/components/Ledgers/Ledgers.columns.js
src/components/Main/Main.js
src/components/Movements/Movements.columns.js
src/components/Orders/Orders.columns.js
src/components/Positions/Positions.columns.js
src/components/PositionsAudit/PositionsAudit.js
src/components/PublicFunding/PublicFunding.columns.js
src/components/PublicTrades/PublicTrades.columns.js
src/components/Tickers/Tickers.columns.js
src/components/Trades/Trades.columns.js
src/components/Wallets/Wallets.columns.js
src/components/Wallets/Wallets.js
src/locales/i18n.js
src/state/audit/reducer.js
src/state/positions/reducer.js
src/state/query/saga.js
src/state/wallets/saga.js
src/styles/index.scss
src/ui/ToggleMenu.js
src/ui/utils.js

Removed base price, liq price, p/l and p/l % from closed positions and positions audited.
Exports language param
Decimals 8 digits formatting, lighter fraction color
Wallets title is changed to `Wallets` instead of `Wallets (Beta)` when sync is enabled
Added `Trailing price` and `Previous type` columns to orders

Numbers formatting, positions columns, emails translation

---

public/index.html
src/styles/index.scss

Local font instead of google cdn

Local roboto font

---

src/components/Positions/Positions.columns.js
src/state/audit/reducer.js
src/state/positions/reducer.js

Adds base price column to closed and audited positions

Positions base price

---

public/locales/ru/translations.json
public/locales/zh-CN/translations.json
public/locales/zh-TW/translations.json
src/styles/index.scss

Adds zebra colors to table rows

Table rows colors

---

src/components/PublicTrades/PublicTrades.js
src/state/publicTrades/reducer.js
src/state/publicTrades/saga.js
src/state/symbols/reducer.js
src/state/symbols/utils.js
src/state/tickers/reducer.js
src/state/utils.js
src/ui/MultiPairSelector/MultiPairSelector.js
src/ui/PairSelector.js
src/ui/SyncPrefButton/SyncPrefButton.container.js

Fixes pairs display and requests

Pairs display and request fix

---

public/locales/ru/translations.json
public/locales/zh-CN/translations.json
public/locales/zh-TW/translations.json
src/components/Timeframe/Timeframe.js
src/state/audit/reducer.js
src/state/fundingCreditHistory/reducer.js
src/state/fundingLoanHistory/reducer.js
src/state/fundingOfferHistory/reducer.js
src/state/fundingPayment/reducer.js
src/state/ledgers/actions.js
src/state/ledgers/reducer.js
src/state/movements/reducer.js
src/state/orders/reducer.js
src/state/positions/reducer.js
src/state/positionsActive/reducer.js
src/state/publicFunding/reducer.js
src/state/publicTrades/reducer.js
src/state/symbols/reducer.js
src/state/tickers/reducer.js
src/state/trades/reducer.js
src/styles/index.scss

Adds error handling to reducers (stops infinite spinners)

Error handling, fixes

---

src/components/Header/Header.js
src/components/PublicFunding/PublicFunding.js
src/components/PublicTrades/PublicTrades.js
src/components/Tickers/Tickers.js
src/components/Wallets/Wallets.js
src/state/auth/saga.js
src/state/query/utils.js
src/state/reducers.js
src/state/sagas.js
src/state/wallets/saga.js
src/state/ws/index.js
src/ui/DateInput/DateInput.js
src/ui/SyncPrefButton/SyncPrefButton.js
src/ui/SyncSymbolPrefButton/SyncSymbolPrefButton.js
src/ui/ToggleMenu.js
src/var/config.js

Merges sync and framework config into one
Disables websockets when framework mode is disabled

Framework config

---

src/state/sync/saga.js
src/state/ws/index.js
src/state/ws/login.js

WS timeouts

---

src/components/Positions/Positions.columns.js

Meta display fix

---

package-lock.json
package.json
src/ui/DataTable.js

Adds headers copying
Fixes `ctrl+c` copying of multiple cells

Headers copying

---

src/state/publicTrades/saga.js
src/state/query/saga.js

Fixes csv export symbols mapping
Fixes double pair mapping in `public trades`

Export symbols mapping

---

src/components/Snapshots/Snapshots.js

Add time picker to the date picker of the position snapshot

Add time selection to position snapshot

---

src/ui/MultiPairSelector/MultiPairSelector.js
src/ui/PairSelector.js

Fixes pair selection with arrow keys
Changes logic for pair filtering

Pair selection

---

package.json
src/state/base/actions.js
src/state/base/reducer.js
src/state/base/saga.js
src/state/ui/saga.js
src/utils/themes.js

Adds ability to set theme and language from query params

Theme and language query params

---

package-lock.json
package.json
src/state/reducers.js

Fixes sync state without framework

Sync state fix

---

src/components/Main/CustomDialog/CustomDialog.js

Fixes app crash on invalid date range in custom date range select

Date range fix

---

public/locales/en-US/translations.json
public/locales/ru/translations.json
public/locales/zh-CN/translations.json
public/locales/zh-TW/translations.json
src/components/TaxReport/Balances.columns.js
src/components/TaxReport/TaxReport.js
src/components/TaxReport/TaxReport.props.js
src/components/TaxReport/TotalMovements.columns.js
src/components/TaxReport/TotalResult.columns.js
src/state/taxReport/reducer.js
src/state/taxReport/selectors.js

Updates tax report section schema:
https://github.com/bitfinexcom/bfx-reports-framework/pull/54

Tax report schema update

---

package-lock.json
package.json

Update package version to 2.14.0 as new features are added.
Fix security vulnerabilities.
Update sub module.

Update package version to 2.14.0

---

src/state/utils.js

Fixes invalid date formatting for values like `null`

Invalid date formatting

---

src/components/ExportDialog/ExportDialog.js
src/state/base/selectors.js

Changes wallets export date format to local

Wallets export date format fix

---

public/locales/ru/translations.json
public/locales/zh-CN/translations.json
public/locales/zh-TW/translations.json
src/ui/ColumnsFilter/ColumnsFilter.js

Filters trim, translations

---

src/styles/index.scss
src/ui/ToggleMenu.js

Fixes nav scroll on small devices

Responsive fix

---

public/locales/en-US/translations.json
src/components/Derivatives/Derivatives.container.js
src/components/Derivatives/Derivatives.js
src/components/Derivatives/Derivatives.props.js
src/state/reducers.helper.js
src/state/symbols/utils.js
src/ui/ColumnsFilter/ColumnsFilter.js
src/ui/ColumnsFilter/_ColumnsFilter.scss
src/ui/MultiPairSelector/MultiPairSelector.container.js
src/ui/MultiPairSelector/MultiPairSelector.js
src/ui/MultiSymbolSelector/MultiSymbolSelector.js

Fixes existing coins and pairs display
Adds filter for derivatives pair selection
Fixes pairs mapping
Adds mark for applied filters

Pairs mapping and display

---

package-lock.json
package.json

Adds script for starting both client and server
Fixes vulnerabilities

Vulnerabilities fix, start script

---

scripts/handleBptIcons.js
src/components/ExportDialog/ExportDialog.js
src/components/Header/Header.js
src/components/Header/_Header.scss
src/components/PrefDialog/PrefDialog.js
src/styles/index.scss
src/ui/Pagination/Pagination.js
src/ui/Pagination/_Pagination.scss
src/ui/QueryLimitSelector/QueryLimitSelector.js
src/ui/SyncPrefButton/SyncPrefButton.js
src/ui/SyncSymbolPrefButton/SyncSymbolPrefButton.js
src/ui/ToggleMenu.js
src/ui/Tooltip/Tooltip.js
src/ui/Tooltip/Tooltip.props.js
src/ui/Tooltip/index.js
src/ui/utils.js

Improves app's responsiveness
Fixes toast's cross icon

Responsive

---

src/state/filters/utils.js
src/state/query/saga.js
src/var/filterTypes.js

Adds filters to exports
Fixes multiple `not equal` filters for the same data

Export filters

---

package.json
public/locales/ru/translations.json
public/locales/zh-CN/translations.json
public/locales/zh-TW/translations.json
scripts/copyEnv.js
scripts/helpers.js

Adds script for .env copying on app start
Adds translations

Translations

---

src/components/AccountBalance/AccountBalance.js
src/components/AverageWinLoss/AverageWinLoss.js
src/components/Main/Main.js
src/state/query/constants.js
src/state/query/saga.js

Adds `Account balance` and `Win/Loss` report exports

Account balance and Win/Loss report exports

---

src/components/PositionsAudit/PositionsAudit.container.js
src/components/PositionsAudit/PositionsAudit.js
src/components/PositionsAudit/PositionsAudit.props.js
src/state/query/utils.js

Positions audit refresh fix

---

src/state/affiliatesEarnings/actions.js
src/state/audit/actions.js
src/state/derivatives/actions.js
src/state/feesReport/actions.js
src/state/fundingCreditHistory/actions.js
src/state/fundingLoanHistory/actions.js
src/state/fundingOfferHistory/actions.js
src/state/fundingPayment/actions.js
src/state/ledgers/actions.js
src/state/loanReport/actions.js
src/state/movements/actions.js
src/state/orderTrades/actions.js
src/state/orders/actions.js
src/state/pagination/actions.js
src/state/positions/actions.js
src/state/positionsActive/actions.js
src/state/publicFunding/actions.js
src/state/publicTrades/actions.js
src/state/query/actions.js
src/state/snapshots/actions.js
src/state/symbols/utils/mapping.js
src/state/sync/actions.js
src/state/tickers/actions.js
src/state/tradedVolume/actions.js
src/state/trades/actions.js
src/state/wallets/actions.js

Fixes repeating `JSDOC` param names

Refactoring

---

public/locales/en-US/translations.json
src/components/Trades/Trades.columns.js
src/ui/ColumnsFilter/ColumnSelector/ColumnSelector.columns.js
src/ui/utils.js

Adds fee percent column to `trades`/`order trades`

Trades fee percent

---

src/components/PositionsActive/PositionsActive.js
src/state/positionsActive/actions.js
src/state/positionsActive/reducer.js

Fixes active positions display

Active positions fix

---

src/components/ExportDialog/ExportDialog.js
src/state/query/saga.js

Fix export email

---

src/state/sync/saga.js

Adds default derivatives config

Add default derivatives config

---

src/ui/Charts/Chart/Chart.js

Adds ability to toggle chart items by clicking legend

Charts legend toggle

---

src/components/AccountBalance/AccountBalance.container.js
src/components/AccountBalance/AccountBalance.js
src/components/AccountBalance/AccountBalance.props.js
src/components/LoanReport/LoanReport.js
src/components/PublicTrades/PublicTrades.container.js
src/components/PublicTrades/PublicTrades.js
src/state/accountBalance/actions.js
src/state/accountBalance/reducer.js
src/state/accountBalance/saga.js
src/state/accountBalance/selectors.js
src/state/affiliatesEarnings/saga.js
src/state/derivatives/reducer.js
src/state/filters/selectors.js
src/state/ledgers/saga.js
src/state/query/actions.js
src/state/sync/saga.js
src/state/utils.js
src/ui/PairSelector/PairSelector.container.js
src/ui/PairSelector/PairSelector.js
src/ui/PairSelector/PairSelector.props.js
src/ui/PairSelector/index.js

Fixes `Derivatives` reset on time range change
Simplifies framework dialog check and pair selector
Fixes `Loan Report` timeframe update
Removes framework dialog check for `Ledgers` and `Affiliates Earnings`

Improvements

---

src/components/Wallets/Wallets.js

Removes date selector from online `wallets`

Wallets date selector

---

.eslintrc.json
src/components/OrderTrades/OrderTrades.NoData.js
src/components/Positions/Positions.js
src/components/PositionsActive/PositionsActive.js
src/components/PositionsAudit/PositionsAudit.NoId.js
src/components/PositionsAudit/PositionsAudit.js
src/components/PublicFunding/PublicFunding.js
src/components/Snapshots/Snapshots.js
src/components/TaxReport/Snapshot/Snapshot.js
src/components/TaxReport/TaxReport.js
src/components/Trades/Trades.columns.js
src/state/utils.js
src/ui/ToggleMenu/ToggleMenu.js

Adds `-` as empty fee percent indicator
Fixes persisting `authToken`
Fixes lint

authToken persist fix

---

src/components/Wallets/Wallets.js

Fix missing platform

---

public/locales/en-US/translations.json
src/state/filters/utils.js
src/ui/ColumnsFilter/FilterTypeSelector/FilterTypeSelector.js
src/var/filterTypes.js

Adds separate filters for `gte` and `lte`

gte and lte filters

---

src/state/reducers.js
src/state/sagas.js
src/ui/ToggleMenu/ToggleMenu.js

Enables `funding payment` for hosted version

Funding payment (hosted version)

---

src/components/AccountSummary/AccountSummary.fees.js
src/components/AccountSummary/AccountSummary.marginFunds.js
src/components/AccountSummary/AccountSummary.volume.js
src/state/reducers.js
src/state/sagas.js
src/ui/ToggleMenu/ToggleMenu.js
src/ui/utils.js

Adds link properties to the main menu
Enables `Affiliates Earnings` section for hosted version
Adds numbers formatting to `Account Summary`

Affiliates Earnings (hosted version)

---

src/components/Ledgers/Ledgers.columns.js
src/state/fundingPayment/saga.js

Fixes funding payment symbol filter

Funding payment symbol filter

---

public/locales/en-US/translations.json

Rename funding payments to funding earnings

Rename funding payments

---

package.json
src/components/Orders/Orders.columns.js
src/components/Orders/Orders.props.js
src/state/orders/reducer.js
src/ui/ColumnsFilter/ColumnSelector/ColumnSelector.columns.js

Add meta orders

---

src/ui/JSONFormat/JSONFormat.js

JSON tooltip fix

---

src/state/symbols/__tests__/utils.mapping.test.js
src/state/symbols/reducer.js
src/state/symbols/utils/mapping.js

Removes `BAB` processing logic

BAB display fix

---

src/state/accountSummary/reducer.js
src/state/accountSummary/selectors.js

Fixes `account summary` response

Account summary

---

src/state/symbols/reducer.js

Fixes `BAB`/`BCH` ID's by mapping `BCH` to `pBCH`

BCH same ID fix

---

src/state/symbols/utils/mapping.js

pBCH mapping fix

---

src/state/symbols/utils/mapping.js

Fix pBCH mapping

---

src/styles/themes/_dark.scss
src/styles/themes/_light.scss
src/ui/MultiSelect/_MultiSelect.scss

Colors update

---

src/components/Positions/Positions.columns.js

Fixes links to positions audit

Position audit link fix

---

public/locales/en-US/translations.json
src/components/AccountSummary/AccountSummary.feeTierVolume.js
src/components/AccountSummary/AccountSummary.js
src/components/AccountSummary/AccountSummary.marginFunds.js
src/components/AccountSummary/_AccountSummary.scss

Adds fee tier volume data to `Account summary`

Fee tier volume

---

src/components/AccountSummary/AccountSummary.js
src/components/ConcentrationRisk/ConcentrationRisk.js
src/components/Snapshots/TickersSnapshot/TickersSnapshot.js
src/components/TaxReport/Result/Result.js
src/components/Wallets/Wallets.data.js
src/ui/DataTable/DataTable.js
src/ui/DataTable/_DataTable.scss

Fixes table height in sections with small tables

Table height fix

---

src/ui/utils.js

Change the reges expression as Safari  doesn't support lookbehind (?<!…)

Fix for Safari

---

public/locales/en-US/translations.json
src/components/Wallets/Wallets.data.js
src/components/Wallets/var/index.js
src/ui/utils.js

Adds data from `Token sales` wallet

Token sales wallet

---

src/components/Main/Main.js

Fixes ledgers symbol selection

Ledgers symbol selection fix

---

src/components/Auth/SignIn/SignIn.js

Adds password reset on account switch

Sign in password fix

---

src/components/Auth/SignUp/SignUp.js

Hides password protection for hosted version

Password protection (hosted version)

---

public/locales/en-US/translations.json
src/ui/LedgersCategorySelect/LedgersCategorySelect.js

Adds `trading rebate` ledgers category

Trading rebate category

---

src/state/ledgers/reducer.js
src/state/ledgers/saga.js

Fixes ledgers request timeframe

Ledgers request timeframe fix

---

src/components/AccountSummary/AccountSummary.fees.js
src/ui/utils.js

Improves fees fraction formatting

Fees fraction formatting

---

src/state/query/saga.js

Adds ledgers categories to export

Ledgers category export

---

src/state/filters/utils.js
src/ui/ColumnsFilter/ColumnSelector/ColumnSelector.columns.js
src/ui/ColumnsFilter/ColumnsFilter.js
src/ui/ColumnsFilter/Selectors/SideSelector.js
src/var/dataTypes.js

Adds side filter to `funding loans` and `funding credits`

Side filter

---

src/state/auth/Authenticator.js

Removes auth token persist after login with api keys

Auth token persist fix

---

src/var/config.js

Redirect link

---

public/locales/en-US/translations.json
src/components/Derivatives/Derivatives.columns.js
src/state/derivatives/reducer.js
src/ui/ColumnsFilter/ColumnSelector/ColumnSelector.columns.js

Adds `Clamp Min` and `Clamp Max` fields to `Derivatives`

Derivatives fields

---

src/state/taxReport/reducer.js

Fixes tax report snapshot loading indicator

Tax report snapshot loading indicator

---

public/locales/en-US/translations.json
src/components/ChangeLogs/ChangeLogs.columns.js
src/components/Derivatives/Derivatives.columns.js
src/components/FundingCreditHistory/FundingCreditHistory.columns.js
src/components/FundingLoanHistory/FundingLoanHistory.columns.js
src/components/Logins/Logins.columns.js
src/state/changeLogs/reducer.js
src/state/filters/utils.js
src/state/logins/reducer.js
src/ui/ColumnsFilter/ColumnSelector/ColumnSelector.columns.js
src/ui/ColumnsFilter/ColumnsFilter.js
src/ui/ColumnsFilter/FilterTypeSelector/FilterTypeSelector.js
src/ui/DateInput/DateInput.js
src/ui/DateInput/DateInput.props.js
src/var/dataTypes.js

Date column filters

---

src/components/Trades/Trades.columns.js
src/state/accountSummary/reducer.js
src/state/accountSummary/selectors.js
src/state/symbols/reducer.js
src/state/symbols/utils/index.js
src/state/symbols/utils/mapping.js
src/state/symbols/var/index.js

Perpetual symbols rename

---

src/components/Auth/SignIn/SignIn.js
src/components/SubAccounts/SubAccount/SubAccount.js

Sub account creation fix

---

public/locales/en-US/translations.json
src/components/Header/TopNavigation/TopNavigation.container.js
src/components/Header/TopNavigation/TopNavigation.js
src/components/Header/TopNavigation/TopNavigation.props.js
src/components/Header/TopNavigation/_TopNavigation.scss
src/index.js
src/styles/index.scss
src/ui/DateRangePicker/DateRangePicker.js
src/ui/DateRangePicker/_DateRangePicker.scss
src/ui/NavMenu/NavMenuPopover/NavMenuPopover.js
src/ui/SectionHeader/_SectionHeader.scss

Improves top navigation and date picker responsive

Top navigation fix

---

public/locales/en-US/translations.json
src/components/Positions/Positions.columns.js

Adds positions `period` funding type

Positions period funding type

---

src/state/symbols/utils/mapping.js

Fix the mapping for descriptions

Fix description mapping

---

public/locales/en-US/translations.json
src/components/AccountSummary/AccountSummary.feeTierVolume.js
src/components/AccountSummary/AccountSummary.js
src/components/AccountSummary/AccountSummary.leo.js
src/components/AccountSummary/AccountSummary.paidFees.js
src/state/query/saga.js
src/state/symbols/utils/mapping.js
src/ui/NoData/_NoData.scss

Updates `Tax report` snapshot export logic
Adds `Account summary` data (leo, trading fees)

Account Summary data

---

package-lock.json
package.json

Adds `cross-env` to ensure the correct setting of environment variable

Config fix

---

src/ui/ColumnsFilter/ColumnSelector/ColumnSelector.columns.js
src/ui/ColumnsFilter/ColumnsFilter.js
src/ui/ColumnsFilter/FilterTypeSelector/FilterTypeSelector.js
src/ui/ColumnsFilter/FilterTypeSelector/FilterTypeSelector.props.js
src/ui/ColumnsFilter/Selectors/WalletSelector.js

Wallet filter

---

public/locales/en-US/translations.json
src/components/Movements/Movements.columns.js
src/state/movements/reducer.js
src/ui/ColumnsFilter/ColumnSelector/ColumnSelector.columns.js

Adds `Note` column to `Movements`

Movements note

---

package-lock.json
package.json
src/components/Logins/Logins.props.js
src/components/OrderTrades/OrderTrades.NoData.js
src/components/Orders/Orders.props.js
src/components/PositionsAudit/PositionsAudit.NoId.js
src/components/TaxReport/Snapshot/Snapshots.props.js
src/ui/NavMenu/NavMenu.props.js
src/ui/SectionHeader/SectionHeader.props.js

Updates `react-scripts`
Fixes prop types

Vulnerabilities fix

---

package.json
src/components/AccountSummary/AccountSummary.paidFees.js
src/components/AccountSummary/_AccountSummary.scss
src/components/Header/TopNavigation/_TopNavigation.scss
src/components/Status/_Status.scss
src/styles/index.scss
src/ui/CollapsedTable/_CollapsedTable.scss
src/ui/DateRangePicker/_DateRangePicker.scss
src/ui/Loading/_Loading.scss
src/ui/MultiSelect/_MultiSelect.scss
src/ui/NavMenu/NavMenu.js
src/ui/NavMenu/_NavMenu.scss
src/ui/NoData/_NoData.scss
src/ui/Pagination/_Pagination.scss
src/ui/SectionHeader/_SectionHeader.scss
src/ui/Select/_Select.scss

Adds mobile view for iphone 12 (390px)
Improves account summary mobile styles

Iphone 12 layout fix

---

src/components/Status/Status.js

Fixes repeated toasts due to i18n updates

Repeated toasts fix

---

src/styles/button.scss
src/styles/themes/_dark.scss
src/styles/themes/_light.scss

Updates dark theme green colours

Dark theme green colour update

---

public/locales/en-US/translations.json
public/locales/es-EM/translations.json
public/locales/ru/translations.json
public/locales/zh-CN/translations.json
public/locales/zh-TW/translations.json
src/ui/Charts/Charts.helpers.js
src/ui/TimeFrameSelector/TimeFrameSelector.js
src/ui/TimeFrameSelector/constants.js

- Implemented week time frame support in `TimeFrameSelector`, updated related helpers, constants and locales
- Depends on [bfx-reports-framework/pull/170](https://github.com/bitfinexcom/bfx-reports-framework/pull/170) 
https://user-images.githubusercontent.com/41899906/124449423-202e5780-dd8c-11eb-857e-2546fef4169c.mov

Add week timeframe

---

public/locales/en-US/translations.json
src/components/Wallets/Wallets.data.js

- Renamed `Token Sales` wallet to `Capital Raise`

(improvement) Rename token sales wallet

---

package-lock.json
package.json

This PR updates the sub module of express

Upd sub module for express

---

package-lock.json
package.json
src/components/AccountBalance/AccountBalance.container.js
src/components/AccountBalance/AccountBalance.js
src/components/AccountBalance/index.js
src/components/Header/AccountMenu/_AccountMenu.scss
src/components/Header/_Header.scss
src/ui/Charts/Chart/Chart.js
src/ui/Charts/Chart/_Chart.scss

- Fixes `Account Balance` charts resizing issues and improved responsiveness
- Optimizes HOCs composition and code readability improvements in related components
https://user-images.githubusercontent.com/41899906/135264443-cbcd1bda-516e-424d-a700-dd0c6e4bae33.mov

(fix) Charts resizing issues

---

src/state/publicFunding/saga.js
src/state/symbols/utils/index.js

- Fixes issues with incorrect symbols formatting while fetching `Public Funding` report for test pairs

(fix) Test funding pairs

---

src/ui/JSONFormat/_JSONFormat.scss

- Fixes `Logins` metadata duplicated data preview on mobiles
https://user-images.githubusercontent.com/41899906/147947859-f9ca20b0-d96f-4cf2-b9ea-5500f4f0ef68.mov

(fix) Duplicated data preview on mobiles

---

src/state/query/saga.js

- Adds `remoteCsvUrn` to export success modal if the related param is available after report generation
- Depends on [bfx-report #256](https://github.com/bitfinexcom/bfx-report/pull/256)

(improvement) Add remote csv urn

---

src/components/Invoices/Invoices.columns.js

- Fixes issues with copying merchant `Payment` data values

(fix) Merchant payment data copy

---

src/components/Auth/PasswordRecovery/PasswordRecovery.js
src/components/Auth/SignUp/SignUp.js
src/config.js

(improvement) Persist password protection for the hosted framework mode

---

package-lock.json
package.json

(internal) Actualize sass compiler

---

package-lock.json
package.json
src/locales/i18n.js

(internal) Actualize  i18next backend

---

src/components/Auth/SignIn/SignIn.container.js
src/components/Auth/SignIn/SignIn.js
src/components/Auth/_Auth.scss
src/state/auth/selectors.js

https://user-images.githubusercontent.com/41899906/167616196-67a8348f-07df-4d93-9f60-11cafcd7e2d4.mov

(improvement) Persist sub accounts

---

src/state/sync/saga.js

https://user-images.githubusercontent.com/41899906/168578722-27fe42da-a277-4654-ac6a-8cf97aaed9c7.mov

(fix) Issue on logout

---

package-lock.json
package.json

- [An issue with installing UI deps](https://app.asana.com/0/1163495710802945/1202393633321991/f)
- [Actualize dependencies](https://app.asana.com/0/1198734617779736/1202092498069641/f) 
- Related to [bfx-report-electron #151](https://github.com/bitfinexcom/bfx-report-electron/pull/151)

(fix) UI dependencies verification

---

public/locales/en/translations.json
src/components/FeesReport/FeesReport.js
src/components/TradedVolume/TradedVolume.js
src/state/feesReport/saga.js
src/state/tradedVolume/saga.js
src/ui/Charts/Chart/Chart.js
src/ui/Charts/Chart/Chart.props.js
src/ui/Charts/Chart/Chart.tooltip.js
src/ui/Charts/Chart/_Chart.scss
src/ui/Charts/Charts.helpers.js

https://user-images.githubusercontent.com/41899906/182598005-cbfea6e4-b97e-4aa6-8d1b-7b8753197cae.mov

(feature) Selectable charts range values sum up

---

package-lock.json
package.json

- Bumps [recharts](https://www.npmjs.com/package/recharts/v/2.1.13) from 2.1.4 to 2.1.13

(internal) Actualize recharts 

---

src/state/columns/saga.js
src/utils/columns.js

https://user-images.githubusercontent.com/41899906/186143517-132a3b2c-42f5-435a-88b4-2519d87b1ea3.mov

(improvement) Numeric columns sum

---

src/state/candles/saga.js
src/state/goToRange/actions.js
src/state/goToRange/constants.js

https://user-images.githubusercontent.com/41899906/186902291-d7483511-c01d-4e17-a1e3-fdc66302b3c8.mov
https://user-images.githubusercontent.com/41899906/186902366-6c8cc67b-e917-46a1-935a-e629cfcba5a6.mov

(improvement) Candles fetching

---

src/state/query/saga.js

Task: https://bitfinex.slack.com/archives/D0210K35PRN/p1665660285967339

(fix) Reports export

---

public/locales/es-EM/translations.json

(improvement) Actualize Spanish translations

---

src/components/Auth/RegisterSubAccounts/RegisterSubAccounts.js
src/components/SubAccounts/SubAccount/SubUsersAdd/_SubUsersAdd.scss

Task: https://app.asana.com/0/1163495710802945/1203359976044126/f
https://user-images.githubusercontent.com/41899906/202141733-fa015aad-204a-4f89-96de-930984322ae7.mov

(improvement) Multiple sub-accounts creations 

---

src/state/auth/reducer.js

Task: https://app.asana.com/0/1198734617779736/1203472343394493/f

(fix) Provide token on sign out

---

dependabot.yml

Task: https://app.asana.com/0/1163495710802945/1202092498069641/f
- Related to #586

(internal) Dependabot configuration

---

package-lock.json
package.json

Reverts bitfinexcom/bfx-report-ui#574

Revert "Bump loader-utils and react-scripts"

---

src/ui/NavMenu/_NavMenu.scss

Task: https://app.asana.com/0/1163495710802945/1203756073451413/f

(fix) Navigation menu representation

---

.npmrc
package-lock.json
package.json
src/components/AccountSummary/AccountSummary.feeTierVolume.js
src/components/AccountSummary/AccountSummary.js
src/components/AffiliatesEarnings/AffiliatesEarnings.link.js
src/components/Auth/Auth.js
src/components/Candles/Candles.js
src/components/Derivatives/Derivatives.js
src/components/Invoices/Invoices.js
src/components/SubAccounts/SubAccount/SubAccountRemove/SubAccountRemove.js
src/components/WeightedAverages/WeightedAverages.js
src/styles/themes/_dark.scss
src/ui/Charts/Candlestick/CandleStats/CandleStats.js
src/ui/Charts/Candlestick/Tooltip/Tooltip.js
src/ui/NoMerchant/NoMerchant.js
src/ui/TimeRange/_TimeRange.scss

Task: https://app.asana.com/0/1163495710802945/1204318814066798/f
- [bfx-report-ui #640](https://github.com/bitfinexcom/bfx-report-ui/pull/640)

(improvement) Selected range representation

---

src/ui/ColumnsFilter/_ColumnsFilter.scss

Task: https://app.asana.com/0/1163495710802945/1204559203795574/f

(fix) Columns filter representation

---

src/components/Auth/RegisterSubAccounts/RegisterSubAccounts.js
src/components/SubAccounts/SubAccount/SubAccount.js
src/components/SubAccounts/SubAccount/SubUsersList/SubUsersList.js
src/components/SubAccounts/SubAccounts.js
src/state/subAccounts/saga.js

Task: https://app.asana.com/0/1163495710802945/1204776097979495/f
https://github.com/bitfinexcom/bfx-report-ui/assets/41899906/53e1f815-20d0-4b89-ade3-d12bbb5ca3f7
- [bfx-reports-framework #288](https://github.com/bitfinexcom/bfx-reports-framework/pull/288)
- [bfx-report-ui #662](https://github.com/bitfinexcom/bfx-report-ui/pull/662)

(improvements) Sub-accounts for password protected users

---

public/locales/en/translations.json
src/components/ErrorDialog/ErrorDialog.constants.js
src/components/ErrorDialog/ErrorDialog.container.js
src/components/ErrorDialog/ErrorDialog.js
src/state/sync/saga.js

Task: https://app.asana.com/0/1163495710802945/1204242048559324/f
&nbsp;
https://github.com/bitfinexcom/bfx-report-ui/assets/41899906/f51dc5e8-2e6c-4e2d-9de2-2ad5e12650ec

(improvements) First sync handling

---

src/state/sync/saga.js

Task: https://app.asana.com/0/1163495710802945/1205580176871474/f
- [bfx-reports-framework #321](https://github.com/bitfinexcom/bfx-reports-framework/pull/321)

(improvements) Sync progress handling

---

src/ui/LangMenu/LangMenu.js

Task: https://bitfinex.slack.com/archives/GAVNZP4RF/p1695985689271899

(fix) Translations: add Vietnamese language

---

.eslintrc.json
package-lock.json
package.json
src/components/AccountSummary/AccountSummary.js
src/components/Auth/LoginOtp/LoginOtp.js
src/components/Auth/RegisterSubAccounts/RegisterSubAccounts.js
src/components/Auth/SignIn/SignIn.js
src/components/Auth/SignInList/SignInList.helpers.js
src/components/SubAccounts/SubAccount/SubAccount.js
src/components/SubAccounts/SubAccount/utils/index.js
src/components/Wallets/Wallets.js
src/state/auth/Authenticator.js
src/state/auth/saga.js
src/state/feesReport/saga.js
src/state/filters/selectors.js
src/state/filters/utils.js
src/state/routing/saga.js
src/state/sync/saga.js
src/state/weightedAverages/reducer.js
src/ui/Charts/Chart/Chart.js
src/ui/ColumnsFilter/ColumnsFilter.helpers.js
src/utils/columns.js

Task: https://app.asana.com/0/1163495710802945/1205580176871470/f

(internal) Replace lodash usage with lib-js-util-base: part1 

---

src/components/AccountBalance/AccountBalance.js
src/components/AccountSummary/AccountSummary.volume.js
src/components/AffiliatesEarnings/AffiliatesEarnings.js
src/components/AppSummary/AppSummary.js
src/components/AverageWinLoss/AverageWinLoss.js
src/components/ChangeLogs/ChangeLogs.js
src/components/ConcentrationRisk/ConcentrationRisk.js
src/components/FeesReport/FeesReport.js
src/components/FundingCreditHistory/FundingCreditHistory.js
src/components/FundingLoanHistory/FundingLoanHistory.js
src/components/FundingOfferHistory/FundingOfferHistory.js
src/components/FundingPayment/FundingPayment.js
src/components/Invoices/Invoices.js
src/components/Ledgers/Ledgers.js
src/components/LoanReport/LoanReport.js
src/components/Logins/Logins.js
src/components/Movements/Movements.js
src/components/OrderTrades/OrderTrades.js
src/components/Orders/Orders.js
src/components/Positions/Positions.js
src/components/PositionsActive/PositionsActive.js
src/components/PositionsAudit/PositionsAudit.js
src/components/PublicFunding/PublicFunding.js
src/components/PublicTrades/PublicTrades.js
src/components/StakingPayments/StakingPayments.js
src/components/Tickers/Tickers.js
src/components/TradedVolume/TradedVolume.js
src/components/Trades/Trades.js
src/state/pagination/reducer.js
src/state/utils.js

Task: https://app.asana.com/0/1163495710802945/1205580176871470/f

(internal) Replace lodash usage with lib-js-util-base: part2

---

src/components/PublicTrades/PublicTrades.columns.js
src/components/Trades/Trades.columns.js
src/state/candles/saga.js

Task: https://app.asana.com/0/1163495710802945/1204865435401041/f
https://github.com/bitfinexcom/bfx-report-ui/assets/41899906/485b6c47-b142-4199-98e9-6dc958589573
https://github.com/bitfinexcom/bfx-report-ui/assets/41899906/896ef12e-7e8c-4dd6-ba39-35bde1899d2a

(fix) Duplicated requests on refresh

---

src/components/Auth/LoginOtp/LoginOtp.js

(fix) Lint error

---

public/locales/vi/translations.json

Already approved here: https://github.com/bitfinexcom/bfx-report-ui/pull/773
@alexstotsky

Missing translations for 2FA

---

src/components/ExportDialog/ExportDialog.helpers.js
src/state/query/saga.js

Task: https://app.asana.com/0/1163495710802945/1206663791456453/f
---
- [bfx-report #347](https://github.com/bitfinexcom/bfx-report/pull/347)

(improvement) Allow PDF export for the web

---

src/ui/NavMenu/NavMenu.helpers.js

Task: https://app.asana.com/0/1163495710802945/1206520910910877/f
```
- Ledgers
- Movements
- Wallets
- Earnings
- Trades
- Orders
- Positions
- Funding
```

(improvement) My History navigation

---

package-lock.json

Task: https://app.asana.com/0/1163495710802945/1207609969507349/f
- [Changelog](https://github.com/micromatch/braces/blob/master/CHANGELOG.md)
- [Commits](https://github.com/micromatch/braces/compare/3.0.2...3.0.3)

(internal) Actualize braces

---

src/components/Derivatives/Derivatives.columns.js
src/components/PublicFunding/PublicFunding.columns.js
src/components/PublicFunding/PublicFunding.js
src/components/PublicTrades/PublicTrades.columns.js
src/components/PublicTrades/PublicTrades.js
src/ui/utils.js

Task: https://app.asana.com/0/1163495710802945/1207548789399740/f
---
- [bfx-report-ui #819](https://github.com/bitfinexcom/bfx-report-ui/pull/819)

(improvements) Market history sections

---

src/ui/LedgersCategorySelect/LedgersCategorySelect.js
src/ui/LedgersCategorySelect/index.js

Task: https://app.asana.com/0/1163495710802945/1207987786710496/f

(improvements) Ledgers category filter

---

src/state/auth/saga.js

Task: https://app.asana.com/0/1163495710802945/1209105137998331/f
---
- [bfx-report #418](https://github.com/bitfinexcom/bfx-report/pull/418)

(fix) Actualize isAuthTokenGenerationError flag processing 

---

public/index.html
src/state/base/saga.js
src/styles/index.scss

Task: https://app.asana.com/0/1163495710802945/1209105137998318/f
https://github.com/user-attachments/assets/b497a5d9-9afd-434e-adcb-e030120cbe91
---
- [bfx-report-electron #478](https://github.com/bitfinexcom/bfx-report-electron/pull/478)

(improvement) Theme setting flow

---

package-lock.json
package.json

Task: https://app.asana.com/0/1163495710802945/1209711858900462/f

(internal) Update deps with vulnerabilities

---

src/components/Header/SyncMode/_SyncMode.scss

Task: https://app.asana.com/0/1163495710802945/1209432249067888/f
---
- [bfx-report-ui #896](https://github.com/bitfinexcom/bfx-report-ui/pull/896)

(improvement) Sync info popup

---

src/components/TaxReport/TaxReport.js
src/state/taxReport/selectors.js

Task: https://app.asana.com/0/home/1198734617779732/1210000839417181
---
- [bfx-reports-framework #449](https://github.com/bitfinexcom/bfx-reports-framework/pull/449)

(improvement) Actualize tax report data handling
