bitfinexcom/bfx-report-ui

src/state/symbols/__tests__/utils.test.js
src/state/symbols/utils.js

context:　https://trello.com/c/uYSl4TUi/231-pairselector-wrongly-show-trx-xxx-pair

fix formatPair for t-prefixed pairs

---

package.json
src/state/utils.js

When applying filter by coin, the authToken appears on the URL
context: https://trello.com/c/3smXQqwV/230-showing-auth-token

hide auth token while apply filter by coin

---

public/locales/en-US/translations.json
public/locales/zh-TW/translations.json
src/components/Movements/Movements.columns.js

This PR
- Add TRANSACTION ID column in movement table
- rename CLOSE to LAST PAYOUT in funding credit
- positions audit description translation fix
context:　https://trello.com/c/lo5dBjnN/233-add-fields

add transactionId column in movement

---

package.json
src/state/symbols/__tests__/utils.test.js
src/state/symbols/utils.js

TRXUSD is not format correctly to tTRXUSD, same as `FUNUSD` etc
context:　https://trello.com/c/uYSl4TUi/231-pairselector-wrongly-show-trx-xxx-pair

formatRawSymbols t/f prefix correctly

---

package.json
src/components/Main/CustomDialog.js
src/components/Main/Main.container.js
src/components/Main/Main.js
src/components/Main/Main.props.js
src/components/SyncPrefButton/SyncPrefButton.container.js
src/components/SyncPrefButton/SyncPrefButton.js
src/components/SyncPrefButton/SyncPrefButton.props.js
src/components/Wallets/Wallets.container.js
src/components/Wallets/Wallets.js
src/components/Wallets/Wallets.props.js
src/state/utils.js

Current datetime selector picks the time with local timezone.
This PR:
- show datetime with user pref timezone in  datetime selector
context: https://trello.com/c/LRqjum9s/240-add-selected-timezone-also-for-time-selector

show datetime with user pref timezone in  datetime selector

---

src/state/__tests__/sagas.helper.test.js
src/state/audit/saga.js
src/state/fundingCreditHistory/saga.js
src/state/fundingLoanHistory/saga.js
src/state/fundingOfferHistory/saga.js
src/state/fundingPayment/saga.js
src/state/ledgers/saga.js
src/state/movements/saga.js
src/state/orders/saga.js
src/state/positions/saga.js
src/state/publicTrades/saga.js
src/state/sagas.helper.js
src/state/tickers/saga.js
src/state/trades/saga.js

This PR
- add `fetchNext` saga helper
- the fetch request will behave the same, unless
- `the result is an empty array but has the nextPage = true property`, call the fetch function again
- take returned `nextPage` value as the fetch function's lastest mts param
- apply to all data request saga except the wallet fetch request (which has different data structure)
- add the related unit tests
context: https://trello.com/c/HbuOvgp9/242-next-request

call nextFetch again when get empty array but has next page

---

package.json
src/components/PositionsActive/PositionsActive.container.js
src/components/PositionsActive/PositionsActive.js

followup of #226, fix menu selection from active positions to positions 
Issue:
1. click the `Positions` from menu list
1. click the `Active` button in button group
1. click the `Closed` button in button group
actual:
the `Ledgers` menu list is marked
expect:
the `Positions` menu list is marked

 fix menu selection from active positions to positions 

---

src/components/Wallets/Wallets.js

The string is changed from `wallets.query` to `wallets.query.title` during migration from react-i18n to i18next

fix wallet query button string

---

src/state/fundingPayment/reducer.js

This PR adds missing USD `amount` and `balance` to funding payment

Add missing USD amount and balance to funding payment

---

src/state/auth/saga.js
src/state/sync/saga.js

Adds faster symbols loading, so the request is sent before any request for data.
Fixes mapping in cases where data was loaded before symbols.
Dependency: https://github.com/bitfinexcom/bfx-reports-framework/pull/52

Faster symbols loading

---

src/state/reducers.js

Enables persist of sync config for `public trades`, `public funding` and `tickers`, which avoids blink of preferences section

Sync data persist

---

src/components/ConcentrationRisk/ConcentrationRisk.columns.js
src/components/ConcentrationRisk/ConcentrationRisk.js
src/components/Derivatives/Derivatives.columns.js
src/components/FundingCreditHistory/FundingCreditHistory.columns.js
src/components/FundingLoanHistory/FundingLoanHistory.columns.js
src/components/FundingOfferHistory/FundingOfferHistory.columns.js
src/components/Ledgers/Ledgers.columns.js
src/components/Movements/Movements.columns.js
src/components/Orders/Orders.columns.js
src/components/Positions/Positions.columns.js
src/components/PublicFunding/PublicFunding.columns.js
src/components/PublicTrades/PublicTrades.columns.js
src/components/Tickers/Tickers.columns.js
src/components/Trades/Trades.columns.js
src/components/Wallets/Wallets.columns.js
src/components/Wallets/Wallets.data.js
src/state/filters/reducer.js
src/state/filters/utils.js
src/state/symbols/reducer.js
src/ui/ColumnsFilter/ColumnSelector/ColumnSelector.columns.js

Adds inactive symbols to pairs selection
Fixes rate filters
Removes `currency` from table copy result: `amount`, `balance`, `fees`
Adds rounding to table copy result whenever displayed value is rounded, for consistency

Inactive symbols, rate filters, data copying

---

src/components/AccountSummary/AccountSummary.fees.js
src/components/AccountSummary/AccountSummary.marginFunds.js
src/components/AccountSummary/AccountSummary.volume.js
src/components/Main/Main.js
src/components/PublicFunding/PublicFunding.columns.js
src/components/PublicTrades/PublicTrades.columns.js
src/state/query/utils.js
src/ui/utils.js

Adds option to format amount with separators for thousands
Adds option to add dollar sign prefix
Adds dollar sign for USD values and thousands formatting to `Account summary`
Sets `Account summary` as a default section

Account summary formatting

---

src/state/symbols/utils/mapping.js

Fix the REGEX description replacement Prevent changing words that have the symbols in them, as to do that only change the beginning/end of a word, consider that pair might be in ()

Fix description replacement

---

src/state/base/constants.js

- Added new options for CSVs that have 4 digit years
- Depends on [bfx-report/pull/228](https://github.com/bitfinexcom/bfx-report/pull/228)

Add date formats with 4 digit years

---

src/state/symbols/utils/mapping.js

- Fixed incorrect symbols mapping in Ledgers `mapDescription` that produces issues with `DOGE` and `MegaDOGE`
- Optimized symbols comparison

(fix) Incorrect symbols mapping in Ledgers description

---

public/locales/en-US/translations.json
public/locales/es-EM/translations.json
public/locales/ru/translations.json
public/locales/tr/translations.json
public/locales/zh-CN/translations.json
public/locales/zh-TW/translations.json
src/components/AverageWinLoss/AverageWinLoss.js
src/components/LoanReport/LoanReport.container.js
src/components/LoanReport/LoanReport.js
src/components/LoanReport/index.js
src/state/winLoss/reducer.js
src/state/winLoss/saga.js
src/state/winLoss/selectors.js
src/ui/Charts/Chart/index.js
src/ui/Charts/Charts.helpers.js
src/ui/Charts/PieChart.js
src/ui/ReportTypeSelector/ReportTypeSelector.js
src/ui/ReportTypeSelector/constants.js
src/ui/ReportTypeSelector/index.js
src/ui/Select/_Select.scss

- Adds the possibility to select `Win/Loss vs Account Balance` report in the `Average Win/Loss` section 
- Updates corresponding logic to receive, handle and represent this report properly
- Optimizes HOCs composition and code readability improvements in several components
- Depends on [bfx-reports-frameworks #196](https://github.com/bitfinexcom/bfx-reports-framework/pull/196) 
https://user-images.githubusercontent.com/41899906/140503793-06d04746-3c9a-46ed-af32-b7a7a7e1b57e.mov

(improvement) Add win/loss vs account balance report

---

src/ui/JSONFormat/_JSONFormat.scss

- Fixes `Logins` metadata preview displaying issues

(fix) Logins metadata preview

---

src/components/Auth/SignIn/SignIn.js

- Prevents users without sub-accounts to sign in `Multiple Accounts` mode 
https://user-images.githubusercontent.com/41899906/151342900-b10e7a40-f975-4ded-a5e1-013004123793.mov
https://user-images.githubusercontent.com/41899906/151342992-e683b6a7-481b-408c-84b7-7bc1fd314053.mov

(improvement) Multi-accounts sign in

---

src/ui/DataTable/DataTable.js

This PR fixes the copy/paste table data issue: there inserts a redundant new line character at the start of every copy (single cell or multi-cell)
To operate with the clipboard there is using WebAPI `Navigator.clipboard` interface
https://w3c.github.io/clipboard-apis/#dom-clipboard-readtext
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard
- the requests for the ability to monitor the user's clipboard will stay anyway
- we can't implement different behavior as ` Permissions.query()` and `Permissions.request()` methods are not stable at the moment https://developer.mozilla.org/en-US/docs/Web/API/Permissions https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API/Using_the_Permissions_API
- the `Clipboard.readText()` and `Clipboard.writeText()` may throw an error …

Fix copy-paste table data issue

---

src/ui/Charts/Candlestick/Candlestick.js
src/ui/Charts/Charts.helpers.js

(improvement) Candles chart prices precisions

---

src/ui/Charts/Candlestick/Tooltip/Tooltip.js
src/ui/Charts/Candlestick/_Candlestick.scss
src/ui/utils.js

(fix) Trades tooltips

---

src/ui/Charts/Candlestick/Candlestick.js
src/ui/Charts/Charts.helpers.js

https://user-images.githubusercontent.com/41899906/166453101-816bdf03-c451-43b3-b6de-16b976e64df4.mov
https://user-images.githubusercontent.com/41899906/166453185-a92f0058-db92-4b12-9f91-04c3f7f9ac56.mov

(improvement) Similar trades

---

public/locales/zh-CN/translations.json

(fix) Exchange chinese translations

---

package-lock.json
package.json

- Bumps [redux](https://www.npmjs.com/package/redux) from 4.0.5 to 4.20.0
- Bumps [react-redux](https://www.npmjs.com/package/react-redux) from 7.2.1 to 8.0.1
- Bumps [redux-persist](https://www.npmjs.com/package/redux-persist) from 5.10.0 to 6.0.0

(internal) Actualize redux libraries

---

package-lock.json
package.json

- Bumps [moment](https://www.npmjs.com/package/moment/v/2.29.3) from 2.29.2 to 2.29.3
- Bumps [moment-timezone](https://www.npmjs.com/package/moment-timezone/v/0.5.34) from 0.5.23 to 0.5.34
- Bumps [@blueprintjs/timezone](https://www.npmjs.com/package/@blueprintjs/timezone/v/3.10.1) from 3.4.0 to 3.10.1

(internal) Actualize timezone libraries 

---

src/ui/Charts/Chart/Chart.js
src/ui/Charts/Charts.helpers.js

(improvement) Charts prices representation

---

src/ui/DateInput/DateInput.container.js
src/ui/DateInput/DateInput.js
src/ui/DateInput/DateInput.props.js
src/ui/DateInput/index.js

(improvement) Selected timezone usage in date inputs

---

src/state/ws/signIn.js

(fix) Refresh auth token when user re-login via WebSockets

---

src/ui/utils.js

(improvement) Account summary values

---

src/ui/ColumnsFilter/ColumnSelector/ColumnSelector.columns.js

(improvement) Show trades id column by default

---

public/locales/en/translations.json
src/state/ws/constants.js
src/state/ws/saga.js

- Depends on [bfx-report #266](https://github.com/bitfinexcom/bfx-report/pull/266) and [bfx-reports-framework #230](https://github.com/bitfinexcom/bfx-reports-framework/pull/230)

(feature) Notify users sync is being paused until connection is resumed

---

src/ui/ColumnsFilter/ColumnSelector/ColumnSelector.columns.js

(fix) Public Funding rate filter param

---

src/state/ws/index.js

(fix) Auth via WebSockets

---

src/components/Auth/Auth.js

Task: https://app.asana.com/0/1163495710802945/1203283175870077/f
https://user-images.githubusercontent.com/41899906/200554052-14bce403-8660-4d3e-902e-05721c979871.mov
https://user-images.githubusercontent.com/41899906/200554083-048c53d9-ae49-4211-98c7-beb692a976df.mov

(improvement) Persist selected auth type

---

src/components/Trades/Trades.columns.js

Task: https://app.asana.com/0/1163495710802945/1203157338507327/f

(improvement) Trades fee percent precision

---

src/components/Auth/Auth.js

Task: https://app.asana.com/0/1163495710802945/1203361820459953/f
https://user-images.githubusercontent.com/41899906/201895168-6c90910e-e366-495b-85f9-94c73841f593.mov
https://user-images.githubusercontent.com/41899906/201895280-03fbd423-b367-4ee5-8a69-2a2bd09e8d22.mov

(fix) Redirection after adding a sub-account

---

src/state/query/saga.js
src/state/query/utils.js

Task: https://app.asana.com/0/1163495710802945/1203402965926244/f

(fix) Time frame params providing

---

src/components/SubAccounts/SubAccount/SubAccount.js

Task: https://app.asana.com/0/1163495710802945/1203425507382730/f

(improvement) Sub-accounts selection

---

src/components/Auth/RegisterSubAccounts/RegisterSubAccounts.js
src/components/SubAccounts/SubAccount/SubAccount.js

Task: https://app.asana.com/0/1163495710802945/1203425677147878/f
- Depends on #576

(fix) Staled master account

---

src/components/SubAccounts/SubAccount/SubAccount.js
src/styles/index.scss

Tasks: 
- https://app.asana.com/0/1163495710802945/1203463910471296/f
- https://app.asana.com/0/1163495710802945/1203472343394494/f
https://user-images.githubusercontent.com/41899906/205055092-23200ad1-8c64-44bb-9e63-687222c867b6.mov
https://user-images.githubusercontent.com/41899906/205055164-b2c13415-109b-42ae-9021-ad09b1c1a5eb.mov

(improvement) Sub-accounts creation

---

src/state/symbols/reducer.js

Tasks: 
- https://app.asana.com/0/1163495710802945/1203481440422500/f
- https://app.asana.com/0/1163495710802945/1203483745286385/f

(fix) USDt symbols and pairs parsing

---

src/config.js

Task: https://app.asana.com/0/1163495710802945/1203497198591291/f
Related to [bfx-report-electron #172](https://github.com/bitfinexcom/bfx-report-electron/pull/172)

(fix) URL to get API keys

---

src/components/Auth/RegisterSubAccounts/RegisterSubAccounts.js
src/components/SubAccounts/SubAccount/SubAccount.js
src/components/SubAccounts/SubAccount/SubUsersAdd/SubUsersAdd.js

Task: https://app.asana.com/0/1163495710802945/1203463910471295/f

(fix) Registered users selection

---

src/state/sync/saga.js

Task: https://app.asana.com/0/1163495710802945/1203493040915772/f

(fix) haveCollsBeenSyncedAtLeastOnce request on the sign in

---

package-lock.json

Task: https://app.asana.com/0/1198734617779736/1202092498069641/f 
- Bumps [decode-uri-component](https://github.com/SamVerschueren/decode-uri-component) from 0.2.0 to 0.2.2
- Bumps [express](https://github.com/expressjs/express) from 4.17.1 to 4.18.2
- Bumps [qs](https://github.com/ljharb/qs) from 6.7.0 to 6.11.0
Note: reopens `Dependabot` updating proposals against `beta` instead of `master`

(internal) Actualize decode-uri-component, qs and express

---

src/state/derivatives/reducer.js

Task: https://app.asana.com/0/1163495710802945/1203800205087029/f
https://user-images.githubusercontent.com/41899906/214562439-6f00bfe8-a57f-4c08-abfd-e74f5393e177.mov
https://user-images.githubusercontent.com/41899906/214562510-15d8f6ca-68b6-4635-afa2-8b488db4fc01.mov

(fix) Derivatives: dropping selected pairs on refresh

---

src/ui/Select/_Select.scss

Task: https://app.asana.com/0/1163495710802945/1204059893810965/f

(fix) Adjust symbol filter

---

src/state/auth/saga.js
src/state/utils.js

Task: https://app.asana.com/0/1163495710802945/1203668664168006/f

(improvement) Rework getUsers request

---

src/state/publicTrades/saga.js
src/state/symbols/reducer.js
src/state/symbols/utils/index.js
src/state/utils.js
src/ui/Select/_Select.scss

Task: https://app.asana.com/0/1163495710802945/1204298582161856/f

(fix) Wrong symbol param for getPublicTrades request

---

src/components/Auth/RegisterSubAccounts/RegisterSubAccounts.js

Task: https://app.asana.com/0/1163495710802945/1204435653795721/f
- [bfx-reports-framework #260](https://github.com/bitfinexcom/bfx-reports-framework/pull/260)

(fix) Selection restricted users for multi accounts

---

src/state/symbols/reducer.js
src/state/symbols/utils/index.js
src/state/symbols/utils/mapping.js

Task: https://app.asana.com/0/1163495710802945/1204485197352810/f
- [bfx-reports-framework #278](https://github.com/bitfinexcom/bfx-reports-framework/pull/278)

(improvements) Symbols and pairs handling

---

.npmrc
package-lock.json
package.json
src/components/AccountSummary/AccountSummary.feeTierVolume.js
src/components/AccountSummary/AccountSummary.js
src/components/AffiliatesEarnings/AffiliatesEarnings.link.js
src/components/Auth/Auth.js
src/components/Candles/Candles.js
src/components/Derivatives/Derivatives.js
src/components/Invoices/Invoices.js
src/components/SubAccounts/SubAccount/SubAccountRemove/SubAccountRemove.js
src/components/WeightedAverages/WeightedAverages.js
src/ui/Charts/Candlestick/CandleStats/CandleStats.js
src/ui/Charts/Candlestick/Tooltip/Tooltip.js
src/ui/NoMerchant/NoMerchant.js

Task: 
https://app.asana.com/0/1163495710802945/1204501873281591/f
https://app.asana.com/0/1163495710802945/1204521029418827/f
```
Node.js: 16.20.0
npm: 8.19.4
```
due to the end of the `Node.js v14.x` branch lifecycle

(internal) Actualize node/npm and related fixes

---

src/state/timeRange/reducer.js

Task: https://app.asana.com/0/1163495710802945/1204559203795582/f
https://github.com/bitfinexcom/bfx-report-ui/assets/41899906/a9c61e5f-fcb5-48a5-b056-5a3feae5960a

(improvement) Dates range preserving

---

public/locales/en/translations.json
src/components/Auth/RegisterSubAccounts/RegisterSubAccounts.js
src/components/Auth/RegisterSubAccounts/_RegisterSubAccounts.scss
src/components/Auth/SignIn/SignIn.js
src/components/Header/AccountMenu/AccountMenu.container.js
src/components/Header/AccountMenu/AccountMenu.js
src/components/SubAccounts/SubAccount/SubAccount.js
src/state/auth/selectors.js
src/state/subAccounts/saga.js

Task: https://app.asana.com/0/1163495710802945/1204388320575679/f
https://github.com/bitfinexcom/bfx-report-ui/assets/41899906/ef63781a-78ec-46ef-9dbd-18d780351ba8
- [bfx-reports-framework #271](https://github.com/bitfinexcom/bfx-reports-framework/pull/271)

(feature) Ability to name multiple accounts

---

src/components/Auth/SignIn/SignIn.js

Task: https://app.asana.com/0/1163495710802945/1204646424446474/f

(fix) Password input on the default screen

---

public/locales/en/translations.json
src/components/WeightedAverages/WeightedAverages.note.js
src/components/WeightedAverages/_WeightedAverages.scss

Task: https://app.asana.com/0/1163495710802945/1204569805902093/f

(improvement) Weighted averages limit note

---

public/locales/en/translations.json
src/components/Wallets/Wallets.js
src/ui/NavMenu/NavMenu.helpers.js
src/ui/NavMenu/NavMenu.js
src/ui/SectionSwitch/SectionSwitch.helpers.js

Task: https://app.asana.com/0/1163495710802945/1204647018050040/f

(improvements) Navigation adjustments

---

src/components/Header/AccountMenu/AccountMenu.js
src/components/Header/TopNavigation/TopNavigation.container.js
src/components/Header/TopNavigation/TopNavigation.js

Task: https://app.asana.com/0/1163495710802945/1204922857120776/f

(fix) Menu options availability

---

src/state/auth/saga.js

Task: https://app.asana.com/0/1163495710802945/1204814230933799/f
```
- register a new account via API key/secret
- after the first sign-in ---> logout
- the incorrect type Login instead of API key will be shown once, before the first page refreshing
```
https://github.com/bitfinexcom/bfx-report-ui/assets/41899906/a7b9d22e-6143-4834-8ef4-d953a36e11dd

(fix) Accounts registration type

---

src/ui/NavMenu/NavMenu.helpers.js

Task: https://app.asana.com/0/1163495710802945/1204861291049130/f

(fix) Wallets section active state

---

public/locales/en/translations.json

Task: https://bitfinex.slack.com/archives/GAVNZP4RF/p1688539176006499

(improvements) Update weighted averages limit note

---

src/components/Header/SyncMode/SyncMode.helpers.js
src/utils/dates.js

Task: https://app.asana.com/0/1163495710802945/1205063274561710/f

(fix) Estimated sync time representation

---

src/state/changeLogs/reducer.js

Task: https://app.asana.com/0/1163495710802945/1205273935454916/f

(fix) Issue with change logs

---

src/ui/CollapsedTable/_CollapsedTable.scss

Task: https://app.asana.com/0/1163495710802945/1205282820751447/f

(improvement) Reports representation on mobile

---

src/state/accountBalance/saga.js
src/state/accountSummary/saga.js
src/state/affiliatesEarnings/saga.js
src/state/audit/saga.js
src/state/auth/saga.js
src/state/candles/saga.js
src/state/changeLogs/saga.js
src/state/derivatives/saga.js
src/state/fundingCreditHistory/saga.js
src/state/fundingLoanHistory/saga.js
src/state/fundingOfferHistory/saga.js
src/state/invoices/saga.js
src/state/ledgers/saga.js
src/state/logins/saga.js
src/state/movements/saga.js
src/state/orderTrades/saga.js
src/state/orders/saga.js
src/state/positions/saga.js
src/state/positionsActive/saga.js
src/state/publicFunding/saga.js
src/state/publicTrades/saga.js
src/state/query/saga.js
src/state/subAccounts/saga.js
src/state/symbols/saga.js
src/state/tickers/saga.js
src/state/trades/saga.js
src/state/weightedAverages/saga.js

Task: https://app.asana.com/0/1163495710802945/1205274879478196/f
- [bfx-report #327](https://github.com/bitfinexcom/bfx-report/pull/327)

(improvements) Error messages

---

src/components/Auth/LoginEmail/LoginEmail.js
src/components/Auth/LoginOtp/LoginOtp.js
src/components/Auth/SignUp/SignUp.js
src/hooks/useKeyDown.js

Task: https://app.asana.com/0/1163495710802945/1205737078890392/f
 
https://github.com/bitfinexcom/bfx-report-ui/assets/41899906/63c831e1-f83d-45dc-b353-50982d68a418

(improvement) Submitting via enter for the 2FA sign-up flow

---

src/components/AccountBalance/AccountBalance.js
src/components/AppSummary/AppSummary.js
src/styles/index.scss

Task: https://bitfinex.slack.com/archives/C024AMXFVPD/p1699977613046249?thread_ts=1699973411.324929&cid=C024AMXFVPD

(improvement) Hide unrealized profit selectors

---

src/components/AppSummary/AppSummary.columns.js
src/components/AppSummary/AppSummary.helpers.js

Task: https://app.asana.com/0/1163495710802945/1205968599642845/f
```
- Hide 0% on balance change if the balance was previously 0 e.g. 
EUR was 0 and then it was deposited all current amount balance 432 balance change is also 432, 
it is confusing for users to have a percentage balance change 0% simply should be removed 
- If the balance change is 0$, then 0% should stay
```

(improvement) Balance change representation

---

src/components/AccountBalance/AccountBalance.js
src/components/AppSummary/AppSummary.js
src/styles/index.scss

Task: https://app.asana.com/0/1163495710802945/1206054378193502/f
- [bfx-reports-framework #340](https://github.com/bitfinexcom/bfx-reports-framework/pull/340)

(improvement) Show unrealized profit selectors

---

public/locales/en/translations.json
src/components/AppSummary/AppSummary.byAsset.js
src/components/AppSummary/AppSummary.columns.js
src/components/AppSummary/AppSummary.fees.js
src/components/AppSummary/AppSummary.helpers.js
src/components/AppSummary/AppSummary.value.js
src/components/AppSummary/_AppSummary.scss
src/state/summaryByAsset/saga.js
src/state/utils.js
src/ui/CollapsedTable/CollapsedTable.js

Task: https://app.asana.com/0/1163495710802945/1206140059050433/f
```
- Added Trading Fees and Funding Earnings
- Updated Balance, Balance Change, Currency and Volume
```
- [bfx-reports-framework #344](https://github.com/bitfinexcom/bfx-reports-framework/pull/344)
- [bfx-report-ui #743](https://github.com/bitfinexcom/bfx-report-ui/pull/743)
- [bfx-report-ui #745](https://github.com/bitfinexcom/bfx-report-ui/pull/745)

(improvements) Summary by asset: actualize columns

---

public/locales/en/translations.json
src/components/AppSummary/AppSummary.byAsset.js
src/components/AppSummary/_AppSummary.scss
src/state/summaryByAsset/saga.js

Task:  https://app.asana.com/0/1163495710802945/1205924412881192/f
https://github.com/bitfinexcom/bfx-report-ui/assets/41899906/eb2db9b3-24aa-447a-8eff-b9ea5a228f09
- [bfx-reports-framework #342](https://github.com/bitfinexcom/bfx-reports-framework/pull/342)

(improvement) Dynamic date range support for summary by asset

---

public/locales/en/translations.json
src/components/AppSummary/AppSummary.byAsset.js
src/components/AppSummary/AppSummary.columns.js
src/components/AppSummary/AppSummary.fees.js
src/components/AppSummary/AppSummary.helpers.js
src/components/AppSummary/AppSummary.value.js
src/components/AppSummary/_AppSummary.scss
src/state/summaryByAsset/saga.js
src/ui/CollapsedTable/CollapsedTable.js

Task: https://app.asana.com/0/1163495710802945/1206138402175082/f
- [bfx-report-ui #741](https://github.com/bitfinexcom/bfx-report-ui/pull/741)

(improvement) Display eligible volume for tier calculation in the account fees

---

public/locales/en/translations.json
src/components/AppSummary/AppSummary.byAsset.js
src/components/AppSummary/AppSummary.columns.js
src/components/AppSummary/_AppSummary.scss
src/state/summaryByAsset/saga.js

Task: https://app.asana.com/0/1163495710802945/1206138402175082/f
- [bfx-report-ui #741](https://github.com/bitfinexcom/bfx-report-ui/pull/741)

(improvement) Temporally remove profits from the summary by asset

---

public/locales/en/translations.json
src/components/AppSummary/AppSummary.byAsset.js
src/components/AppSummary/AppSummary.columns.js
src/components/AppSummary/_AppSummary.scss
src/state/summaryByAsset/saga.js
src/state/utils.js

Task: https://app.asana.com/0/1163495710802945/1206140059051450/f
- [bfx-report-ui #744](https://github.com/bitfinexcom/bfx-report-ui/pull/744)

(improvement) Summary by asset: show a selected period as a subtitle

---

src/components/AppSummary/AppSummary.columns.js

Task: https://app.asana.com/0/1163495710802945/1206168266409447/f

(fix) Parent cell height related warnings

---

package-lock.json

Task: https://app.asana.com/0/1198734617779736/1202092498069641/f 
- [Release notes](https://github.com/follow-redirects/follow-redirects/releases)
- [Commits](https://github.com/follow-redirects/follow-redirects/compare/v1.15.3...v1.15.4)
- dependency-name: follow-redirects
- dependency-type: indirect
Note: reopens `dependabot` updating proposals against `staging` instead of `master`

 (internal) Actualize follow-redirects

---

package-lock.json
src/ui/Select/Select.js

Task: https://app.asana.com/0/1163495710802945/1205580176871470/f

(internal) Migrate from Lodash to the lib-js-util-base 

---

src/components/Movements/Movements.js
src/components/Wallets/Wallets.js
src/ui/NavMenu/NavMenu.helpers.js
src/ui/SectionSwitch/SectionSwitch.helpers.js

Task: https://app.asana.com/0/1163495710802945/1206520910910874/f
```
- Remove tabs from wallets & movements
- Make movements a separate navigation item under "My History"
```

(improvement) Movements navigation

---

src/ui/NavSwitcher/NavSwitcher.js
src/ui/NavSwitcher/NavSwitcher.props.js
src/ui/NavSwitcher/index.js

Task: https://app.asana.com/0/1163495710802945/1207599240564860/f

(improvements) Navigation switcher

---

src/components/Derivatives/Derivatives.columns.js
src/components/Invoices/Invoices.columns.js
src/components/PublicFunding/PublicFunding.columns.js
src/components/PublicFunding/PublicFunding.js
src/components/PublicTrades/PublicTrades.columns.js
src/components/PublicTrades/PublicTrades.js
src/ui/JSONFormat/_JSONFormat.scss
src/ui/utils.js
src/utils/columns.js

Task: https://app.asana.com/0/1163495710802945/1207599240564865/f
---
- [bfx-report-ui #823](https://github.com/bitfinexcom/bfx-report-ui/pull/823)

(improvements) Invoices configuration getters

---

src/state/sync/saga.js

Task: https://app.asana.com/0/1163495710802945/1207814579692859/f

(fix) Showing the sync state when the scheduler launches the sync

---

src/components/Auth/LoginOtp/LoginOtp.js

Task: https://app.asana.com/0/1163495710802945/1207921781725071/f
https://github.com/user-attachments/assets/3cb5c920-fd3d-4e8f-a6db-08b6cdadbd92
https://github.com/user-attachments/assets/b7510f26-a472-4ab5-836c-6713bd6166bf

(fix) OTP login request duplication possibility

---

src/components/Movements/Movements.columns.js
src/components/OrderTrades/OrderTrades.js
src/components/Orders/Orders.columns.js
src/components/Positions/Positions.columns.js
src/components/Trades/Trades.columns.js
src/components/Trades/Trades.js
src/utils/columns.js

Task: https://app.asana.com/0/1163495710802945/1208008094081008/f

(improvements) My history sections

---

public/locales/en/translations.json
src/components/Auth/SignUp/SignUp.container.js
src/components/Auth/SignUp/SignUp.js
src/components/Status/_Status.scss

Task: https://app.asana.com/0/1163495710802945/1208244802296793/f
https://github.com/user-attachments/assets/2b117525-b7ed-466c-a9ee-1977a1e4dc04

(improvements) Notifications and auth flow when users try to re-add the existing account

---

public/locales/en/translations.json
src/components/AppSummary/AppSummary.columns.js

Tasks:
https://app.asana.com/0/1163495710802945/1208499237324980/f
https://app.asana.com/0/1163495710802945/1208499237324987/f

(improvements) Assets summary section

---

src/components/AppDownload/AppDownload.helpers.js
src/var/electronVersion.js

Task: https://app.asana.com/0/1163495710802945/1208936141912656/f
https://github.com/user-attachments/assets/d881113c-36b0-43ee-8b59-7ebfe92c3c16
https://github.com/user-attachments/assets/d7e50d6f-9de6-4ca8-8739-ffbf3a7d6ad0

(improvement) Actualize app download link generation

---

src/state/sync/saga.js

Tasks:
https://app.asana.com/0/1163495710802945/1209854016880889/f 
https://app.asana.com/0/1163495710802945/1209841971150296/f
https://github.com/user-attachments/assets/1566829e-0b64-4546-85e0-4da781c9b7a8
https://github.com/user-attachments/assets/ab3fc267-60c8-4405-8c51-d034ad64021e

(improvements) App logout flow during the sync

---

public/locales/en/translations.json
src/state/symbols/reducer.js

Task: https://app.asana.com/0/1163495710802945/1209711858900462/f
---
- [bfx-reports-framework #438](https://github.com/bitfinexcom/bfx-reports-framework/pull/438)
- [bfx-report-ui #909](https://github.com/bitfinexcom/bfx-report-ui/pull/909)

(improvement) Derivative currencies formatting

---

public/locales/en/translations.json

Task: https://app.asana.com/0/1163495710802945/1209711858900469/f
---
- [bfx-reports-framework #438](https://github.com/bitfinexcom/bfx-reports-framework/pull/438)

(improvement) Extend tax reports sources support

---

src/components/ConcentrationRisk/ConcentrationRisk.container.js
src/components/ConcentrationRisk/ConcentrationRisk.js

Task: https://app.asana.com/0/home/1198734617779732/1209855454923406
https://github.com/user-attachments/assets/61f21bfe-8324-4ed9-a5f9-6eadfbc6f771

(improvements) Concentration Risk during initial sync

---

src/components/Snapshots/Snapshots.container.js
src/components/Snapshots/Snapshots.js
src/components/Snapshots/Snapshots.props.js

Task: https://app.asana.com/0/home/1198734617779732/1210379600312641

(improvements) Snapshots during initial sync

---

src/state/query/saga.js

Task: https://app.asana.com/0/home/1198734617779732/1210878359791667
---
- [bfx-reports-framework #466](https://github.com/bitfinexcom/bfx-reports-framework/pull/466)
- [bfx-report #438](https://github.com/bitfinexcom/bfx-report/pull/438)

(fix) Actualize getPositionsAuditFile query params
